### ISSUE TITLE
ERROR from Waldur site agent - https://waldurpoc/api/marketplace-provider-resources/c0bdea7f8f7e4e6e98cae28507bab42f/set_as_ok/. Status: 404. Reason: Not Found.

### ISSUE THREAD

**Issue by tyagisanjeev1211** [waldur/waldur-homeport#71]
Error message:
Server refuses to communicate. URL https://waldurpoc/api/marketplace-provider-resources/c0bdea7f8f7e4e6e98cae28507bab42f/set_as_ok/. Status: 404. Reason: Not Found.
Error traceback:
Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/waldur_site_agent/agent_report.py", line 185, in _process_resources self.waldur_rest_client.marketplace_provider_resource_set_as_ok( File "/usr/local/lib/python3.11/site-packages/waldur_client/__init__.py", line 1131, in marketplace_provider_resource_set_as_ok return self._post(url, valid_states=[200]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/waldur_client/__init__.py", line 382, in _post return self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/waldur_client/__init__.py", line 326, in _make_request raise WaldurClientException(self._parse_error(response)) waldur_client.WaldurClientException: Server refuses to communicate. URL https://waldurpoc/api/marketplace-provider-resources/c0bdea7f8f7e4e6e98cae28507bab42f/set_as_ok/. Status: 404. Reason: Not Found.

**Comment by livenson** [comment]
Please upgrade version of mastermind - or - the agent. This bug was fixed some time ago.

Another issue might be that the token you use in the agent doesn't have owner rights in the service provider organization. You can try accessing the resource from the URL directly, 404 basically means that permissions do not allow it.
